# Generated by Django 5.0.6 on 2024-06-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='libelle',
            new_name='name',
        ),
    ]
