# Generated by Django 5.0.6 on 2024-06-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
