# Generated by Django 5.0.6 on 2024-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0003_alter_pack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='oldPrix',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pack',
            name='duree',
            field=models.IntegerField(),
        ),
    ]
