# Generated by Django 5.0.6 on 2024-06-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='descritpion',
            new_name='description',
        ),
    ]
