# Generated by Django 5.0.6 on 2024-06-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0003_remove_curriculum_slug_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecole.curriculum'),
        ),
    ]
