# Generated by Django 5.0.6 on 2024-06-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0004_stream_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecole.school'),
        ),
    ]
