# Generated by Django 5.0.6 on 2024-07-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0005_level_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursus', to='ecole.school'),
        ),
        migrations.AlterField(
            model_name='level',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='ecole.school'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='ecole.curriculum'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filierescu', to='ecole.level'),
        ),
        migrations.AlterField(
            model_name='test',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epreuvescur', to='ecole.curriculum'),
        ),
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epreuveslevel', to='ecole.level'),
        ),
        migrations.AlterField(
            model_name='test',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epreuvesstream', to='ecole.stream'),
        ),
    ]
