# Generated by Django 5.0.6 on 2024-07-03 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0006_alter_curriculum_school_alter_level_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveauxcur', to='ecole.curriculum'),
        ),
    ]
