# Generated by Django 5.0.6 on 2024-07-03 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0007_alter_level_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolep', to='ecole.school'),
        ),
    ]
