# Generated by Django 5.0.6 on 2024-07-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0004_pack_oldprix_alter_pack_duree'),
        ('panier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='abonnement.pack'),
        ),
    ]
