# Generated by Django 5.0.6 on 2024-06-05 17:06

import django.db.models.deletion
import django.views.generic.list
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecole', '0005_level_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPack',
            fields=[
                ('school_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecole.school')),
            ],
            bases=(django.views.generic.list.ListView, 'ecole.school'),
        ),
    ]
